POST http://127.0.0.1:3000/auth/register HTTP/1.1
content-type: application/json

{
  "email" : "s1@mail.com",
  "password" : "password",
  "accountType" : ["student"],
  "status" : false
  
}

// pass access_token of admin